export interface AirportInfo {
    iata: string;
    lon: string;
    iso: string;
    status: number;
    name: string;
    continent: string;
    type: string;
    lat: string;
    size: string;
}
export var airports: AirportInfo[] = [
    {
        'iata': 'UTK',
        'lon': '169.86667',
        'iso': 'MH',
        'status': 1,
        'name': 'Utirik Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '11.233333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'FIV',
        'iso': 'US',
        'status': 1,
        'name': 'Five Finger CG Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'FAK',
        'iso': 'US',
        'status': 1,
        'name': 'False Island Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'BWS',
        'iso': 'US',
        'status': 0,
        'name': 'Blaine Municipal Airport',
        'continent': 'NA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'WKK',
        'lon': '-158.61111',
        'iso': 'US',
        'status': 1,
        'name': 'Aleknagik \/ New Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '59.27778',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'TSS',
        'iso': 'US',
        'status': 1,
        'name': 'East 34th Street Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'FOB',
        'lon': '-123.79444',
        'iso': 'US',
        'status': 1,
        'name': 'Fort Bragg Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '39.474445',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ABP',
        'lon': '141.1',
        'iso': 'PG',
        'status': 1,
        'name': 'Atkamba Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.066667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ALV',
        'iso': 'AD',
        'status': 1,
        'name': 'Andorra la Vella Heliport',
        'continent': 'EU',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'ADC',
        'lon': '145.73334',
        'iso': 'PG',
        'status': 1,
        'name': 'Andakombe Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.133333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'TJP',
        'lon': '-66.563545',
        'iso': 'PR',
        'status': 1,
        'name': 'Areopuerto Internacional Michael Gonzalez',
        'continent': 'NA',
        'type': 'airport',
        'lat': '18.010702',
        'size': 'large'
    } as AirportInfo,
    {
        'iata': 'AEE',
        'iso': 'SS',
        'status': 1,
        'name': 'Adareil Airport',
        'continent': 'AF',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AEI',
        'iso': 'ES',
        'status': 1,
        'name': 'Algeciras Heliport',
        'continent': 'EU',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'AEK',
        'lon': '146.28334',
        'iso': 'PG',
        'status': 1,
        'name': 'Aseki Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.366667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'OLR',
        'lon': '36.130333',
        'iso': 'AF',
        'status': 1,
        'name': 'Salerno Landing Zone Airport',
        'continent': 'AS',
        'type': 'airport',
        'lat': '34.023167',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AFR',
        'lon': '148.38333',
        'iso': 'PG',
        'status': 1,
        'name': 'Afore Airstrip',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.133333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AFT',
        'lon': '160.85',
        'iso': 'SB',
        'status': 1,
        'name': 'Afutara Aerodrome',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.2',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ATD',
        'lon': '161.03334',
        'iso': 'SB',
        'status': 1,
        'name': 'Uru Harbour Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.866667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'VEV',
        'lon': '159.55',
        'iso': 'SB',
        'status': 1,
        'name': 'Barakoma Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.85',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'GEF',
        'lon': '156.59778',
        'iso': 'SB',
        'status': 1,
        'name': 'Geva Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.578333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AGG',
        'lon': '144.07388',
        'iso': 'PG',
        'status': 1,
        'name': 'Angoram Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-4.168611',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AKS',
        'lon': '160.68083',
        'iso': 'SB',
        'status': 1,
        'name': 'Auki Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.697778',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BAS',
        'lon': '155.88333',
        'iso': 'SB',
        'status': 1,
        'name': 'Ballalae Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.983333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'FRE',
        'lon': '159.58333',
        'iso': 'SB',
        'status': 1,
        'name': 'Fera\/Maringe Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.1',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'HIR',
        'lon': '160.04819',
        'iso': 'SB',
        'status': 1,
        'name': 'Honiara International Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.428592',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'MBU',
        'lon': '160.75',
        'iso': 'SB',
        'status': 1,
        'name': 'Babanakira Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.733333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'IRA',
        'lon': '161.83333',
        'iso': 'SB',
        'status': 1,
        'name': 'Ngorangora Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-10.5',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'SCZ',
        'lon': '166.85',
        'iso': 'SB',
        'status': 1,
        'name': 'Santa Cruz\/Graciosa Bay\/Luova Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-11.616667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MUA',
        'lon': '157.26971',
        'iso': 'SB',
        'status': 1,
        'name': 'Munda Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.32794',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'GZO',
        'lon': '156.83333',
        'iso': 'SB',
        'status': 1,
        'name': 'Nusatupe Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.116667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MNY',
        'lon': '155.56462',
        'iso': 'SB',
        'status': 1,
        'name': 'Mono Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.417428',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'PRS',
        'lon': '158.0',
        'iso': 'SB',
        'status': 1,
        'name': 'Parasi Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.166667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'OTV',
        'iso': 'SB',
        'status': 0,
        'name': 'Ontong Java Atoll Airstrip',
        'continent': 'OC',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'RNL',
        'lon': '160.3',
        'iso': 'SB',
        'status': 1,
        'name': 'Rennell\/Tingoa Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-11.666667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'EGM',
        'lon': '157.87506',
        'iso': 'SB',
        'status': 1,
        'name': 'Sege Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.577956',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'RUS',
        'lon': '161.25',
        'iso': 'SB',
        'status': 1,
        'name': 'Marau Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.5',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'VAO',
        'lon': '158.66667',
        'iso': 'SB',
        'status': 1,
        'name': 'Suavanao Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.566667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AGK',
        'lon': '143.84666',
        'iso': 'PG',
        'status': 1,
        'name': 'Kagua Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.403333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KGE',
        'lon': '157.5861',
        'iso': 'SB',
        'status': 1,
        'name': 'Kagau Island Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.165',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AGL',
        'lon': '149.15527',
        'iso': 'PG',
        'status': 1,
        'name': 'Wanigela Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.340278',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'RIN',
        'lon': '157.03334',
        'iso': 'SB',
        'status': 1,
        'name': 'Ringi Cove Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.2',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'RBV',
        'lon': '157.63945',
        'iso': 'SB',
        'status': 1,
        'name': 'Ramata Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.165556',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AHT',
        'iso': 'US',
        'status': 0,
        'name': 'Amchitka Army Airfield',
        'continent': 'NA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'AHY',
        'lon': '45.533333',
        'iso': 'MG',
        'status': 1,
        'name': 'Ambatolhy Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-20.016666',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AIE',
        'lon': '144.66667',
        'iso': 'PG',
        'status': 1,
        'name': 'Aiome Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.166667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AIH',
        'lon': '141.26639',
        'iso': 'PG',
        'status': 1,
        'name': 'Aiambak Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.348611',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AIP',
        'lon': '168.81667',
        'iso': 'MH',
        'status': 1,
        'name': 'Ailinglaplap Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '7.266667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AOS',
        'iso': 'US',
        'status': 1,
        'name': 'Amook Bay Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'AKM',
        'lon': '19.816668',
        'iso': 'TD',
        'status': 1,
        'name': 'Zakuoma Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '10.883333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ALZ',
        'iso': 'US',
        'status': 1,
        'name': 'Alitak Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'AME',
        'lon': '37.583332',
        'iso': 'MZ',
        'status': 1,
        'name': 'Alto Molocue Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-15.833333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AMF',
        'lon': '141.66667',
        'iso': 'PG',
        'status': 1,
        'name': 'AMA Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-4.166667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AMU',
        'lon': '141.15',
        'iso': 'PG',
        'status': 1,
        'name': 'Amanab Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-3.516667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AMY',
        'lon': '45.666668',
        'iso': 'MG',
        'status': 1,
        'name': 'Ambatomainty Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-17.683332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ANH',
        'iso': 'SB',
        'status': 0,
        'name': 'Anuha Island Resort Airport',
        'continent': 'OC',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'INU',
        'lon': '166.91667',
        'iso': 'NR',
        'status': 1,
        'name': 'Nauru International Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-0.533333',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'ANL',
        'lon': '17.25',
        'iso': 'AO',
        'status': 1,
        'name': 'Andulo Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-11.25',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CNZ',
        'lon': '19.0',
        'iso': 'AO',
        'status': 1,
        'name': 'Cangamba Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-11.5',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'DRC',
        'lon': '20.7',
        'iso': 'AO',
        'status': 1,
        'name': 'Dirico Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-17.833332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'GGC',
        'lon': '22.566668',
        'iso': 'AO',
        'status': 1,
        'name': 'Lumbala Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-12.65',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'JMB',
        'lon': '16.083332',
        'iso': 'AO',
        'status': 1,
        'name': 'Jamba Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-14.7',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KNP',
        'lon': '15.450278',
        'iso': 'AO',
        'status': 1,
        'name': 'Capanda Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-9.766944',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'NDF',
        'lon': '14.833333',
        'iso': 'AO',
        'status': 1,
        'name': 'Ndalatandos Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-9.333333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AOB',
        'lon': '144.65',
        'iso': 'PG',
        'status': 1,
        'name': 'Annanberg Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-4.916667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'APP',
        'lon': '148.13333',
        'iso': 'PG',
        'status': 1,
        'name': 'Asapa Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.983333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'APR',
        'lon': '145.0',
        'iso': 'PG',
        'status': 1,
        'name': 'April River Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.5',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AQY',
        'lon': '-149.11667',
        'iso': 'US',
        'status': 1,
        'name': 'Girdwood Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '60.966667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'QRF',
        'lon': '-60.466667',
        'iso': 'AR',
        'status': 1,
        'name': 'Bragado Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-35.13333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CSZ',
        'lon': '-61.88333',
        'iso': 'AR',
        'status': 1,
        'name': 'Brigadier Hector Ruiz Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-37.433334',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CVI',
        'lon': '-67.416664',
        'iso': 'AR',
        'status': 1,
        'name': 'Caleta Olivia Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-46.416668',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CNT',
        'lon': '-61.233334',
        'iso': 'AR',
        'status': 1,
        'name': 'Charata Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-27.216667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'VGS',
        'lon': '-63.0',
        'iso': 'AR',
        'status': 1,
        'name': 'General Villegas Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-35.083332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'LMD',
        'lon': '-68.13333',
        'iso': 'AR',
        'status': 1,
        'name': 'Los Menucos Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-40.833332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'VCF',
        'lon': '-66.15',
        'iso': 'AR',
        'status': 1,
        'name': 'Valcheta Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-40.7',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'VME',
        'lon': '-65.416664',
        'iso': 'AR',
        'status': 1,
        'name': 'Villa Mercedes Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-33.63333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'NCJ',
        'iso': 'AR',
        'status': 1,
        'name': 'Sunchales Aeroclub Airport',
        'continent': 'SA',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CPG',
        'lon': '-62.979782',
        'iso': 'AR',
        'status': 1,
        'name': 'Carmen De Patagones Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-40.782757',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'PRQ',
        'lon': '-60.666668',
        'iso': 'AR',
        'status': 1,
        'name': 'Termal Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-26.833332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ARP',
        'lon': '149.5',
        'iso': 'PG',
        'status': 1,
        'name': 'Aragip Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.8',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'TAV',
        'lon': '-169.45',
        'iso': 'AS',
        'status': 1,
        'name': 'Tau Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-14.25',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ASZ',
        'lon': '150.36667',
        'iso': 'PG',
        'status': 1,
        'name': 'Asirim Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.866667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ATP',
        'lon': '142.28334',
        'iso': 'PG',
        'status': 1,
        'name': 'Aitape Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-3.166667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AGW',
        'lon': '142.15',
        'iso': 'AU',
        'status': 1,
        'name': 'Agnew Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-12.15',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AYD',
        'lon': '135.95',
        'iso': 'AU',
        'status': 1,
        'name': 'Alroy Downs Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-19.3',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BCK',
        'lon': '144.16667',
        'iso': 'AU',
        'status': 1,
        'name': 'Bolwarra Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-17.4',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BFC',
        'lon': '145.33333',
        'iso': 'AU',
        'status': 1,
        'name': 'Bloomfield Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-15.9',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BVW',
        'lon': '143.21666',
        'iso': 'AU',
        'status': 1,
        'name': 'Batavia Downs Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-12.65',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BYX',
        'lon': '136.23334',
        'iso': 'AU',
        'status': 1,
        'name': 'Baniyala Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-13.2',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'COB',
        'lon': '130.93333',
        'iso': 'AU',
        'status': 1,
        'name': 'Coolibah Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-15.55',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CQP',
        'lon': '147.5',
        'iso': 'AU',
        'status': 1,
        'name': 'Cape Flattery Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-18.2',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CRJ',
        'lon': '132.3',
        'iso': 'AU',
        'status': 1,
        'name': 'Coorabie Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-31.9',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CRY',
        'lon': '128.61667',
        'iso': 'AU',
        'status': 1,
        'name': 'Carlton Hill Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-15.466667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CSD',
        'lon': '135.91667',
        'iso': 'AU',
        'status': 1,
        'name': 'Cresswell Downs Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-17.966667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CTR',
        'lon': '131.0',
        'iso': 'AU',
        'status': 1,
        'name': 'Cattle Creek Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-17.583332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'DYM',
        'lon': '139.16667',
        'iso': 'AU',
        'status': 1,
        'name': 'Diamantina Lakes Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-26.75',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'EDD',
        'lon': '133.2',
        'iso': 'AU',
        'status': 1,
        'name': 'Erldunda Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-25.25',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'EKD',
        'lon': '135.55',
        'iso': 'AU',
        'status': 1,
        'name': 'Elkedra Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-21.15',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'HAT',
        'lon': '140.58333',
        'iso': 'AU',
        'status': 1,
        'name': 'Heathlands Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-19.720833',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'HIG',
        'lon': '143.15',
        'iso': 'AU',
        'status': 1,
        'name': 'Highbury Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-16.416668',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'HIS',
        'iso': 'AU',
        'status': 1,
        'name': 'Hayman Island Resort Seaplane Base',
        'continent': 'OC',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'HLV',
        'lon': '145.2',
        'iso': 'AU',
        'status': 1,
        'name': 'Helenvale Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-15.683333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KBD',
        'lon': '124.35',
        'iso': 'AU',
        'status': 1,
        'name': 'Kimberley Downs Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-17.333332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KGR',
        'lon': '133.03334',
        'iso': 'AU',
        'status': 1,
        'name': 'Kulgera Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-25.833332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KOH',
        'lon': '142.41667',
        'iso': 'AU',
        'status': 1,
        'name': 'Koolatah Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-15.966667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KYF',
        'lon': '120.075',
        'iso': 'AU',
        'status': 1,
        'name': 'Yeelirrie Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-27.277779',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'LIB',
        'lon': '129.8',
        'iso': 'AU',
        'status': 1,
        'name': 'Limbunya Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-17.2',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MNW',
        'lon': '135.21666',
        'iso': 'AU',
        'status': 1,
        'name': 'Macdonald Downs Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-22.45',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MUP',
        'lon': '141.05',
        'iso': 'AU',
        'status': 1,
        'name': 'Mulga Park Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-31.133333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MWY',
        'lon': '141.51666',
        'iso': 'AU',
        'status': 1,
        'name': 'Miranda Downs Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-25.783333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MYO',
        'lon': '124.26667',
        'iso': 'AU',
        'status': 1,
        'name': 'Camballin Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-18.116667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'NKB',
        'lon': '124.85',
        'iso': 'AU',
        'status': 1,
        'name': 'Noonkanbah Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-18.55',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'OKB',
        'lon': '153.16667',
        'iso': 'AU',
        'status': 1,
        'name': 'Orchid Beach Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-25.25',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'PEP',
        'lon': '130.1',
        'iso': 'AU',
        'status': 1,
        'name': 'Peppimenarti Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-14.15',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'RDA',
        'lon': '135.16667',
        'iso': 'AU',
        'status': 1,
        'name': 'Rockhampton Downs Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-18.95',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'SSK',
        'lon': '128.13333',
        'iso': 'AU',
        'status': 1,
        'name': 'Sturt Creek Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-19.2',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'SWB',
        'lon': '119.36667',
        'iso': 'AU',
        'status': 1,
        'name': 'Shaw River Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-21.516666',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'TPR',
        'lon': '117.666664',
        'iso': 'AU',
        'status': 1,
        'name': 'Tom Price Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-22.75',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'TWP',
        'lon': '143.75',
        'iso': 'AU',
        'status': 1,
        'name': 'Torwood Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-17.366667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'WRW',
        'lon': '120.71667',
        'iso': 'AU',
        'status': 1,
        'name': 'Warrawagine Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-20.866667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'WSY',
        'lon': '148.75278',
        'iso': 'AU',
        'status': 1,
        'name': 'Whitsunday Airstrip',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-20.502777',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ZVG',
        'lon': '127.583336',
        'iso': 'AU',
        'status': 1,
        'name': 'Springvale Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-17.866667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AUI',
        'lon': '143.075',
        'iso': 'PG',
        'status': 1,
        'name': 'Aua Island Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-1.458333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AUJ',
        'lon': '142.85',
        'iso': 'PG',
        'status': 1,
        'name': 'Ambunti Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-4.25',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AUP',
        'lon': '149.58333',
        'iso': 'PG',
        'status': 1,
        'name': 'Agaun Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.983333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'AUV',
        'lon': '148.43333',
        'iso': 'PG',
        'status': 1,
        'name': 'Aumo Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.716667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BUA',
        'lon': '154.67288',
        'iso': 'PG',
        'status': 1,
        'name': 'Buka Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.422443',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'CMU',
        'lon': '144.97444',
        'iso': 'PG',
        'status': 1,
        'name': 'Chimbu Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.993889',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'DAU',
        'lon': '143.20605',
        'iso': 'PG',
        'status': 1,
        'name': 'Daru Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.08351',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'GKA',
        'lon': '145.39293',
        'iso': 'PG',
        'status': 1,
        'name': 'Goroka Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.075244',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'GUR',
        'lon': '150.33861',
        'iso': 'PG',
        'status': 1,
        'name': 'Gurney Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-10.310833',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'PNP',
        'lon': '148.30873',
        'iso': 'PG',
        'status': 1,
        'name': 'Girua Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.807474',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'HKN',
        'lon': '150.403',
        'iso': 'PG',
        'status': 1,
        'name': 'Kimbe Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.456876',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'LSA',
        'lon': '151.025',
        'iso': 'PG',
        'status': 1,
        'name': 'Losuia Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-8.363889',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'UNG',
        'lon': '141.28601',
        'iso': 'PG',
        'status': 1,
        'name': 'Kiunga Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.125552',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KRI',
        'lon': '144.26666',
        'iso': 'PG',
        'status': 1,
        'name': 'Kikori Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.483333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KMA',
        'lon': '145.77155',
        'iso': 'PG',
        'status': 1,
        'name': 'Kerema Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-7.961702',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'KVG',
        'lon': '150.80653',
        'iso': 'PG',
        'status': 1,
        'name': 'Kavieng Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-2.58075',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'LNV',
        'lon': '152.6272',
        'iso': 'PG',
        'status': 1,
        'name': 'Londolovit Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-3.043223',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MAG',
        'lon': '145.78784',
        'iso': 'PG',
        'status': 1,
        'name': 'Madang Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.210852',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'HGU',
        'lon': '144.29738',
        'iso': 'PG',
        'status': 1,
        'name': 'Mount Hagen Kagamuga Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.828767',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'MDU',
        'lon': '143.65',
        'iso': 'PG',
        'status': 1,
        'name': 'Mendi Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.158611',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'MAS',
        'lon': '147.42444',
        'iso': 'PG',
        'status': 1,
        'name': 'Momote Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-2.056667',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'MXH',
        'lon': '143.25055',
        'iso': 'PG',
        'status': 1,
        'name': 'Moro Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.3525',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MIS',
        'lon': '152.84166',
        'iso': 'PG',
        'status': 1,
        'name': 'Misima Island Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-10.5',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'LAE',
        'lon': '146.72757',
        'iso': 'PG',
        'status': 1,
        'name': 'Lae Nadzab Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.562694',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'POM',
        'lon': '147.21446',
        'iso': 'PG',
        'status': 1,
        'name': 'Port Moresby Jacksons International Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-9.444308',
        'size': 'large'
    } as AirportInfo,
    {
        'iata': 'TIZ',
        'lon': '142.94055',
        'iso': 'PG',
        'status': 1,
        'name': 'Tari Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.860556',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'TBG',
        'lon': '141.227',
        'iso': 'PG',
        'status': 1,
        'name': 'Tabubil Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.274722',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'RAB',
        'lon': '152.36667',
        'iso': 'PG',
        'status': 1,
        'name': 'Tokua Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-4.333333',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'AYU',
        'lon': '145.9',
        'iso': 'PG',
        'status': 1,
        'name': 'Aiyura Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-6.333333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'VAI',
        'lon': '141.30194',
        'iso': 'PG',
        'status': 1,
        'name': 'Vanimo Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-2.694722',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'WBM',
        'lon': '143.91667',
        'iso': 'PG',
        'status': 1,
        'name': 'Wapenamanda Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-5.616667',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'WWK',
        'lon': '143.66916',
        'iso': 'PG',
        'status': 1,
        'name': 'Wewak International Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-3.580034',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'AYY',
        'iso': 'LK',
        'status': 1,
        'name': 'Arugam Bay SPB',
        'continent': 'AS',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'AYZ',
        'iso': 'US',
        'status': 0,
        'name': 'Zahn\'s Airport',
        'continent': 'NA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'AZB',
        'lon': '148.81667',
        'iso': 'PG',
        'status': 1,
        'name': 'Amazon Bay Airport',
        'continent': 'OC',
        'type': 'airport',
        'lat': '-10.15',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BCW',
        'lon': '35.425',
        'iso': 'MZ',
        'status': 1,
        'name': 'Benguera Island Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-21.884722',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'HKV',
        'lon': '25.55',
        'iso': 'BG',
        'status': 1,
        'name': 'Haskovo Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '41.933334',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'JAM',
        'lon': '26.483334',
        'iso': 'BG',
        'status': 1,
        'name': 'Bezmer Air Base',
        'continent': 'EU',
        'type': 'airport',
        'lat': '42.516666',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'SZR',
        'iso': 'BG',
        'status': 0,
        'name': 'Stara Zagora Airport',
        'continent': 'EU',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JEG',
        'lon': '-52.75',
        'iso': 'GL',
        'status': 1,
        'name': 'Aasiaat Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '68.7',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'AAP',
        'iso': 'GL',
        'status': 1,
        'name': 'Aappilattoq (Qaasuitsup) Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'AGM',
        'iso': 'GL',
        'status': 1,
        'name': 'Tasiilaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'LLU',
        'iso': 'GL',
        'status': 1,
        'name': 'Alluitsup Paa Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'QUV',
        'iso': 'GL',
        'status': 1,
        'name': 'Aappilattoq (Kujalleq) Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'QUW',
        'iso': 'GL',
        'status': 1,
        'name': 'Ammassivik Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'QGQ',
        'iso': 'GL',
        'status': 1,
        'name': 'Attu Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'UAK',
        'lon': '-45.316666',
        'iso': 'GL',
        'status': 1,
        'name': 'Narsarsuaq Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '61.166668',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'JCH',
        'iso': 'GL',
        'status': 1,
        'name': 'Qasigiannguit Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'CNP',
        'lon': '-22.658333',
        'iso': 'GL',
        'status': 1,
        'name': 'Neerlerit Inaat Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '70.74306',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'QFG',
        'iso': 'GL',
        'status': 1,
        'name': 'Eqalugaarsuit Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'QFN',
        'iso': 'GL',
        'status': 1,
        'name': 'Narsaq Kujalleq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JFR',
        'iso': 'GL',
        'status': 1,
        'name': 'Paamiut Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'GOH',
        'lon': '-51.725',
        'iso': 'GL',
        'status': 1,
        'name': 'Godthaab \/ Nuuk Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '64.181946',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'JGO',
        'iso': 'GL',
        'status': 1,
        'name': 'Qeqertarsuaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'IKE',
        'iso': 'GL',
        'status': 1,
        'name': 'Ikerasak Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'QFI',
        'iso': 'GL',
        'status': 1,
        'name': 'Iginniarfik',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'XIQ',
        'iso': 'GL',
        'status': 1,
        'name': 'Ilimanaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'INN',
        'iso': 'GL',
        'status': 1,
        'name': 'Innarsuit Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'ISO',
        'iso': 'GL',
        'status': 1,
        'name': 'Isortoq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'QJI',
        'iso': 'GL',
        'status': 1,
        'name': 'Ikamiut Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JJU',
        'iso': 'GL',
        'status': 1,
        'name': 'Qaqortoq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JAV',
        'lon': '-51.05991',
        'iso': 'GL',
        'status': 1,
        'name': 'Ilulissat Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '69.24186',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'QPW',
        'iso': 'GL',
        'status': 1,
        'name': 'Kangaatsiaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'KUS',
        'lon': '-37.11667',
        'iso': 'GL',
        'status': 1,
        'name': 'Kulusuk Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '65.566666',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'UPK',
        'iso': 'GL',
        'status': 1,
        'name': 'Upernavik Kujalleq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'KMT',
        'iso': 'GL',
        'status': 1,
        'name': 'Kuummiut Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'KLQ',
        'iso': 'GL',
        'status': 1,
        'name': 'Kullorsuaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'KAQ',
        'iso': 'GL',
        'status': 1,
        'name': 'Kangersuatsiaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'QJE',
        'iso': 'GL',
        'status': 1,
        'name': 'Kitsissuarsuit Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'ILL',
        'iso': 'GL',
        'status': 1,
        'name': 'Illorsuit Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'MOR',
        'iso': 'GL',
        'status': 1,
        'name': 'Moriusaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JSU',
        'lon': '-52.93537',
        'iso': 'GL',
        'status': 1,
        'name': 'Maniitsoq Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '65.41244',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'QMK',
        'iso': 'GL',
        'status': 1,
        'name': 'Niaqornaarsuk Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JNN',
        'iso': 'GL',
        'status': 1,
        'name': 'Nanortalik Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'NUG',
        'iso': 'GL',
        'status': 1,
        'name': 'Nuugaatsiaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JNS',
        'iso': 'GL',
        'status': 1,
        'name': 'Narsaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'NIA',
        'iso': 'GL',
        'status': 1,
        'name': 'Niaqornat Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'NUS',
        'iso': 'GL',
        'status': 1,
        'name': 'Nuussuaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JFR',
        'lon': '-49.70028',
        'iso': 'GL',
        'status': 1,
        'name': 'Paamiut Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '62.00028',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'QQT',
        'iso': 'GL',
        'status': 1,
        'name': 'Qeqertaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'NAQ',
        'lon': '-69.382996',
        'iso': 'GL',
        'status': 1,
        'name': 'Qaanaaq Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '77.48948',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'OBY',
        'iso': 'GL',
        'status': 1,
        'name': 'Ittoqqortoormiit Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'SFJ',
        'lon': '-50.719723',
        'iso': 'GL',
        'status': 1,
        'name': 'Kangerlussuaq Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '67.01222',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'SMG',
        'iso': 'GL',
        'status': 1,
        'name': 'Sermiligaaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'SIO',
        'iso': 'GL',
        'status': 1,
        'name': 'Siorapaluk Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'QUP',
        'iso': 'GL',
        'status': 1,
        'name': 'Saqqaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JHS',
        'lon': '-53.704166',
        'iso': 'GL',
        'status': 1,
        'name': 'Sisimiut Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '66.93694',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'SAA',
        'iso': 'GL',
        'status': 1,
        'name': 'Saattut Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'SAV',
        'iso': 'GL',
        'status': 1,
        'name': 'Savissivik Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'THU',
        'lon': '-68.7',
        'iso': 'GL',
        'status': 1,
        'name': 'Thule Air Base',
        'continent': 'NA',
        'type': 'airport',
        'lat': '76.53333',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'TNT',
        'iso': 'GL',
        'status': 1,
        'name': 'Tiniteqilaaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JUV',
        'lon': '-56.130554',
        'iso': 'GL',
        'status': 1,
        'name': 'Upernavik Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '72.790276',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'UMD',
        'iso': 'GL',
        'status': 1,
        'name': 'Uummannaq Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'JQA',
        'lon': '-52.702778',
        'iso': 'GL',
        'status': 1,
        'name': 'Qaarsut Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '70.73194',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'UKK',
        'iso': 'GL',
        'status': 1,
        'name': 'Ukkusissat Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'AEY',
        'lon': '-18.075068',
        'iso': 'IS',
        'status': 1,
        'name': 'Akureyri Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '65.654564',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'BIU',
        'lon': '-23.983334',
        'iso': 'IS',
        'status': 1,
        'name': 'Bildudalur Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '65.833336',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BLO',
        'lon': '-20.3',
        'iso': 'IS',
        'status': 1,
        'name': 'Hjaltabakki Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '65.666664',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'HFN',
        'lon': '-15.266667',
        'iso': 'IS',
        'status': 1,
        'name': 'Hornafjordur Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '64.28333',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'FLI',
        'lon': '-23.7',
        'iso': 'IS',
        'status': 1,
        'name': 'Holt Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '65.98333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'HZK',
        'lon': '-17.427778',
        'iso': 'IS',
        'status': 1,
        'name': 'Husavik Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '65.95528',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'KEF',
        'lon': '-22.624283',
        'iso': 'IS',
        'status': 1,
        'name': 'Keflavik International Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '63.997765',
        'size': 'large'
    } as AirportInfo,
    {
        'iata': 'PFJ',
        'lon': '-19.008333',
        'iso': 'IS',
        'status': 1,
        'name': 'Patreksfjordur Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '65.03333',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'OLI',
        'lon': '-23.983334',
        'iso': 'IS',
        'status': 1,
        'name': 'Rif Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '65.0',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'REK',
        'iso': 'IS',
        'status': 1,
        'name': 'Reykjavik Airport',
        'continent': 'EU',
        'type': 'airport',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'SIJ',
        'lon': '-18.933332',
        'iso': 'IS',
        'status': 1,
        'name': 'Siglufjordur Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '66.166664',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'THO',
        'lon': '-15.335653',
        'iso': 'IS',
        'status': 1,
        'name': 'Thorshofn Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '66.219734',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'VEY',
        'lon': '-20.277779',
        'iso': 'IS',
        'status': 1,
        'name': 'Vestmannaeyjar Airport',
        'continent': 'EU',
        'type': 'airport',
        'lat': '63.426388',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'BJE',
        'iso': 'SD',
        'status': 1,
        'name': 'Baleela Airport',
        'continent': 'AF',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BJQ',
        'iso': 'OM',
        'status': 1,
        'name': 'Bahja Airport',
        'continent': 'AS',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BLM',
        'lon': '-74.01667',
        'iso': 'MX',
        'status': 1,
        'name': 'Bahia De Los Angelos South',
        'continent': 'NA',
        'type': 'airport',
        'lat': '40.183334',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BMQ',
        'lon': '39.833332',
        'iso': 'KE',
        'status': 1,
        'name': 'Bamburi Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-4.5',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'RBQ',
        'lon': '-67.55',
        'iso': 'BO',
        'status': 1,
        'name': 'Rurenabaque Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-14.45',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BVL',
        'lon': '-63.583332',
        'iso': 'BO',
        'status': 1,
        'name': 'Baures Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-13.583333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ALT',
        'iso': 'BR',
        'status': 0,
        'name': 'Alenquer Airport',
        'continent': 'SA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'SWM',
        'iso': 'BR',
        'status': 0,
        'name': 'Suia-Missu Airport',
        'continent': 'SA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'NSB',
        'iso': 'BS',
        'status': 1,
        'name': 'Bimini North Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'HUK',
        'lon': '21.75',
        'iso': 'BW',
        'status': 1,
        'name': 'Hukuntsi Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-23.983334',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BYV',
        'iso': 'LK',
        'status': 1,
        'name': 'Beira Lake Seaplane Base',
        'continent': 'AS',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'BCV',
        'lon': '-88.77904',
        'iso': 'BZ',
        'status': 1,
        'name': 'Belmopan Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '17.270498',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'BGK',
        'lon': '-88.4',
        'iso': 'BZ',
        'status': 1,
        'name': 'Big Creek Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '16.516666',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'CUK',
        'lon': '-88.02956',
        'iso': 'BZ',
        'status': 1,
        'name': 'Caye Caulker Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '17.735527',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'CYC',
        'lon': '-88.833336',
        'iso': 'BZ',
        'status': 1,
        'name': 'Caye Chapel Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '17.666668',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'CZH',
        'lon': '-88.410675',
        'iso': 'BZ',
        'status': 1,
        'name': 'Corozal Municipal Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '18.382334',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'DGA',
        'lon': '-88.23039',
        'iso': 'BZ',
        'status': 1,
        'name': 'Dangriga Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '16.982765',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'INB',
        'lon': '-88.43826',
        'iso': 'BZ',
        'status': 1,
        'name': 'Independence Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '16.535536',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'MDB',
        'lon': '-88.32056',
        'iso': 'BZ',
        'status': 1,
        'name': 'Melinda Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '16.998611',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ORZ',
        'lon': '-88.75',
        'iso': 'BZ',
        'status': 1,
        'name': 'Orange Walk Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '17.166668',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'PLJ',
        'lon': '-88.360886',
        'iso': 'BZ',
        'status': 1,
        'name': 'Placencia Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '16.53708',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'PND',
        'lon': '-88.816666',
        'iso': 'BZ',
        'status': 1,
        'name': 'Punta Gorda Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '16.1',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'SJX',
        'lon': '-88.333336',
        'iso': 'BZ',
        'status': 1,
        'name': 'Sartaneja Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '18.3',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'SPR',
        'lon': '-87.96571',
        'iso': 'BZ',
        'status': 1,
        'name': 'San Pedro Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '17.917067',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'SQS',
        'lon': '-89.03333',
        'iso': 'BZ',
        'status': 1,
        'name': 'Matthew Spain Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '17.183332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'STU',
        'lon': '-88.45',
        'iso': 'BZ',
        'status': 1,
        'name': 'Santa Cruz Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '18.266666',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'SVK',
        'lon': '-88.34',
        'iso': 'BZ',
        'status': 1,
        'name': 'Silver Creek Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '16.7253',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'TZA',
        'lon': '-88.191666',
        'iso': 'BZ',
        'status': 1,
        'name': 'Belize City Municipal Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '17.51639',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'BZB',
        'lon': '35.49167',
        'iso': 'MZ',
        'status': 1,
        'name': 'Bazaruto Island Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-21.534721',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YUJ',
        'iso': 'CA',
        'status': 0,
        'name': 'Lady Franklin Point Airport',
        'continent': 'NA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YWO',
        'iso': 'CA',
        'status': 0,
        'name': 'Lupin Airport',
        'continent': 'NA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YTJ',
        'iso': 'CA',
        'status': 0,
        'name': 'Terrace Bay Airport',
        'continent': 'NA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YMV',
        'iso': 'CA',
        'status': 1,
        'name': 'Mary River Aerodrome',
        'continent': 'NA',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YBW',
        'iso': 'CA',
        'status': 1,
        'name': 'Bedwell Harbour Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'ZNA',
        'iso': 'CA',
        'status': 1,
        'name': 'Nanaimo Harbour Water Airport',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YZZ',
        'lon': '-117.6',
        'iso': 'CA',
        'status': 1,
        'name': 'Trail Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.066666',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YWS',
        'iso': 'CA',
        'status': 1,
        'name': 'Whistler\/Green Lake Water Aerodrome',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YPT',
        'iso': 'CA',
        'status': 1,
        'name': 'Pender Harbour Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YAA',
        'lon': '-125.3',
        'iso': 'CA',
        'status': 1,
        'name': 'Anahim Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.45',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'JHL',
        'lon': '-111.41889',
        'iso': 'CA',
        'status': 1,
        'name': 'Fort MacKay\/Albian Aerodrome',
        'continent': 'NA',
        'type': 'airport',
        'lat': '57.22389',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YMU',
        'iso': 'CA',
        'status': 1,
        'name': 'Mansons Landing Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YWM',
        'lon': '-56.01282',
        'iso': 'CA',
        'status': 1,
        'name': 'Williams Harbour Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.335438',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YFX',
        'lon': '-55.683334',
        'iso': 'CA',
        'status': 1,
        'name': 'St. Lewis (Fox Harbour) Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.36667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YHA',
        'lon': '-56.3',
        'iso': 'CA',
        'status': 1,
        'name': 'Port Hope Simpson Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.533333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YRG',
        'lon': '-58.416668',
        'iso': 'CA',
        'status': 1,
        'name': 'Rigolet Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '54.333332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CDK',
        'lon': '-83.03333',
        'iso': 'US',
        'status': 1,
        'name': 'George T Lewis Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '29.133333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YCK',
        'lon': '-126.09047',
        'iso': 'CA',
        'status': 1,
        'name': 'Colville Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '67.03993',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'EE7',
        'iso': 'CA',
        'status': 1,
        'name': 'Edmonton\/Cooking Lake Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'NML',
        'iso': 'CA',
        'status': 1,
        'name': 'Fort McMurray \/ Mildred Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'DAS',
        'lon': '-119.712776',
        'iso': 'CA',
        'status': 1,
        'name': 'Great Bear Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '66.70306',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YFI',
        'iso': 'CA',
        'status': 1,
        'name': 'Fort Mackay \/ Firebag',
        'continent': 'NA',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'OKG',
        'lon': '15.0',
        'iso': 'CG',
        'status': 1,
        'name': 'Okoyo Airport',
        'continent': 'AF',
        'type': 'airport',
        'lat': '-1.466667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CGA',
        'iso': 'US',
        'status': 1,
        'name': 'Craig Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'SUR',
        'lon': '-88.5475',
        'iso': 'CA',
        'status': 1,
        'name': 'Summer Beaver Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.71528',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YAX',
        'lon': '-89.565',
        'iso': 'CA',
        'status': 1,
        'name': 'Wapekeka Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '53.251945',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'WNN',
        'lon': '-89.166664',
        'iso': 'CA',
        'status': 1,
        'name': 'Wunnumin Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.916668',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YNO',
        'lon': '-92.416664',
        'iso': 'CA',
        'status': 1,
        'name': 'North Spirit Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.5',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'CLG',
        'iso': 'US',
        'status': 0,
        'name': 'Coalinga Airport',
        'continent': 'NA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'OHE',
        'lon': '122.42059',
        'iso': 'CN',
        'status': 1,
        'name': 'Gu-Lian Airport',
        'continent': 'AS',
        'type': 'airport',
        'lat': '52.92113',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'FUO',
        'lon': '113.28333',
        'iso': 'CN',
        'status': 1,
        'name': 'Foshan Shadi Airport',
        'continent': 'AS',
        'type': 'airport',
        'lat': '23.133333',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'HUZ',
        'lon': '114.36667',
        'iso': 'CN',
        'status': 1,
        'name': 'Huizhou Airport',
        'continent': 'AS',
        'type': 'airport',
        'lat': '23.083332',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'JGS',
        'lon': '114.7375',
        'iso': 'CN',
        'status': 1,
        'name': 'Jinggangshan Airport',
        'continent': 'AS',
        'type': 'airport',
        'lat': '26.899721',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'AEB',
        'lon': '106.96777',
        'iso': 'CN',
        'status': 1,
        'name': 'Tian Yang Air Base',
        'continent': 'AS',
        'type': 'airport',
        'lat': '23.71947',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'AAT',
        'lon': '88.08444',
        'iso': 'CN',
        'status': 1,
        'name': 'Altay Air Base',
        'continent': 'AS',
        'type': 'airport',
        'lat': '47.750362',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YZY',
        'lon': '100.660835',
        'iso': 'CN',
        'status': 1,
        'name': 'Zhangye Southeast Air Base',
        'continent': 'AS',
        'type': 'airport',
        'lat': '38.8075',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'DDG',
        'lon': '124.28081',
        'iso': 'CN',
        'status': 1,
        'name': 'Dandong Airport',
        'continent': 'AS',
        'type': 'airport',
        'lat': '40.032368',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'NTG',
        'lon': '120.9756',
        'iso': 'CN',
        'status': 1,
        'name': 'Nantong Airport',
        'continent': 'AS',
        'type': 'airport',
        'lat': '32.07292',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'XBE',
        'lon': '-90.98333',
        'iso': 'CA',
        'status': 1,
        'name': 'Bearskin Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '53.95',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'KIF',
        'lon': '-89.85',
        'iso': 'CA',
        'status': 1,
        'name': 'Kingfisher Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '53.01389',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YOG',
        'lon': '-85.916664',
        'iso': 'CA',
        'status': 1,
        'name': 'Ogoki Post Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '51.666668',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'PRM',
        'iso': 'CO',
        'status': 1,
        'name': 'Proma Heliport',
        'continent': 'SA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'ISG',
        'iso': 'CO',
        'status': 1,
        'name': 'Isa Giron Heliport',
        'continent': 'SA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'API',
        'lon': '-73.05194',
        'iso': 'CO',
        'status': 1,
        'name': 'Apiay Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '4.068889',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'ARQ',
        'lon': '-71.43166',
        'iso': 'CO',
        'status': 1,
        'name': 'El Troncal Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '7.033056',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'LCR',
        'lon': '-73.01667',
        'iso': 'CO',
        'status': 1,
        'name': 'La Chorrera Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '-0.733333',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'SNT',
        'lon': '-73.0',
        'iso': 'CO',
        'status': 1,
        'name': 'Las Cruces Airport',
        'continent': 'SA',
        'type': 'airport',
        'lat': '7.666667',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YEB',
        'iso': 'CA',
        'status': 1,
        'name': 'Bar River Airport',
        'continent': 'NA',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YHP',
        'lon': '-94.3',
        'iso': 'CA',
        'status': 1,
        'name': 'Poplar Hill Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.083332',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YNX',
        'iso': 'CA',
        'status': 1,
        'name': 'Snap Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YKU',
        'lon': '-78.924065',
        'iso': 'CA',
        'status': 1,
        'name': 'Chisasibi Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '53.806824',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YAU',
        'lon': '-73.31694',
        'iso': 'CA',
        'status': 1,
        'name': 'Donaldson Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '61.662777',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'TR7',
        'iso': 'CA',
        'status': 1,
        'name': 'Ottawa \/ Rockcliffe Seaplane Base',
        'continent': 'NA',
        'type': 'seaplanes',
        'size': null
    } as AirportInfo,
    {
        'iata': 'PST',
        'lon': '-75.666664',
        'iso': 'CU',
        'status': 1,
        'name': 'Preston Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '20.75',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'NIC',
        'iso': 'CY',
        'status': 0,
        'name': 'Nicosia International Airport',
        'continent': 'AS',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YAC',
        'lon': '-91.816666',
        'iso': 'CA',
        'status': 1,
        'name': 'Cat Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '51.716667',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAG',
        'lon': '-93.44722',
        'iso': 'CA',
        'status': 1,
        'name': 'Fort Frances Municipal Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '48.65278',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAH',
        'lon': '-73.65',
        'iso': 'CA',
        'status': 1,
        'name': 'La Grande-4 Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '53.75',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAL',
        'lon': '-126.916664',
        'iso': 'CA',
        'status': 1,
        'name': 'Alert Bay Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '50.583332',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAM',
        'lon': '-84.49995',
        'iso': 'CA',
        'status': 1,
        'name': 'Sault Ste Marie Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '46.485302',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'XKS',
        'lon': '-88.64667',
        'iso': 'CA',
        'status': 1,
        'name': 'Kasabonika Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '53.52',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YKG',
        'lon': '-70.0046',
        'iso': 'CA',
        'status': 1,
        'name': 'Kangirsuk Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '60.023083',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAT',
        'lon': '-82.4',
        'iso': 'CA',
        'status': 1,
        'name': 'Attawapiskat Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.941666',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAV',
        'lon': '-123.3',
        'iso': 'CA',
        'status': 1,
        'name': 'Winnipeg \/ St. Andrews Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '48.86667',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAW',
        'iso': 'CA',
        'status': 1,
        'name': 'Halifax \/ CFB Shearwater Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YAX',
        'lon': '-89.565',
        'iso': 'CA',
        'status': 1,
        'name': 'Lac Du Bonnet Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '53.251945',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAY',
        'lon': '-55.583332',
        'iso': 'CA',
        'status': 1,
        'name': 'St Anthony Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '51.36667',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YAZ',
        'lon': '-125.77639',
        'iso': 'CA',
        'status': 1,
        'name': 'Tofino \/ Long Beach Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.076942',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBB',
        'lon': '-89.85',
        'iso': 'CA',
        'status': 1,
        'name': 'Kugaaruk Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '68.88333',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBC',
        'lon': '-68.26667',
        'iso': 'CA',
        'status': 1,
        'name': 'Baie Comeau Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.2',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'QBC',
        'lon': '-126.666664',
        'iso': 'CA',
        'status': 1,
        'name': 'Bella Coola Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.333332',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBE',
        'lon': '-108.48333',
        'iso': 'CA',
        'status': 1,
        'name': 'Uranium City Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '59.566666',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBY',
        'lon': '-110.73333',
        'iso': 'CA',
        'status': 1,
        'name': 'Bonnyville Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '54.266666',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBG',
        'lon': '-70.98861',
        'iso': 'CA',
        'status': 1,
        'name': 'CFB Bagotville',
        'continent': 'NA',
        'type': 'airport',
        'lat': '48.322224',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBK',
        'lon': '-96.083336',
        'iso': 'CA',
        'status': 1,
        'name': 'Baker Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '64.3',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBL',
        'lon': '-125.26813',
        'iso': 'CA',
        'status': 1,
        'name': 'Campbell River Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.951725',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBN',
        'iso': 'CA',
        'status': 1,
        'name': 'CFB Borden',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'XTL',
        'lon': '-98.51344',
        'iso': 'CA',
        'status': 1,
        'name': 'Tadoule Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '58.707954',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBR',
        'lon': '-99.94677',
        'iso': 'CA',
        'status': 1,
        'name': 'Brandon Municipal Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.908688',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBT',
        'lon': '-101.67899',
        'iso': 'CA',
        'status': 1,
        'name': 'Brochet Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '57.88847',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBV',
        'lon': '-97.02141',
        'iso': 'CA',
        'status': 1,
        'name': 'Berens River Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '52.358696',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YBX',
        'lon': '-57.216667',
        'iso': 'CA',
        'status': 1,
        'name': 'Lourdes de Blanc Sablon Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '51.433334',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YRF',
        'lon': '-57.03828',
        'iso': 'CA',
        'status': 1,
        'name': 'Cartwright Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '53.682606',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCB',
        'lon': '-105.13333',
        'iso': 'CA',
        'status': 1,
        'name': 'Cambridge Bay Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '69.1',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCC',
        'lon': '-74.566666',
        'iso': 'CA',
        'status': 1,
        'name': 'Cornwall Regional Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '45.1',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCD',
        'lon': '-123.86667',
        'iso': 'CA',
        'status': 1,
        'name': 'Nanaimo Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.05',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCE',
        'lon': '-81.48333',
        'iso': 'CA',
        'status': 1,
        'name': 'James T. Field Memorial Aerodrome',
        'continent': 'NA',
        'type': 'airport',
        'lat': '43.283333',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCG',
        'lon': '-117.632225',
        'iso': 'CA',
        'status': 1,
        'name': 'Castlegar\/West Kootenay Regional Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.295555',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCH',
        'lon': '-65.44744',
        'iso': 'CA',
        'status': 1,
        'name': 'Miramichi Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '47.014008',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCL',
        'lon': '-66.32881',
        'iso': 'CA',
        'status': 1,
        'name': 'Charlo Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '47.99093',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCN',
        'lon': '-81.01289',
        'iso': 'CA',
        'status': 1,
        'name': 'Cochrane Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.106018',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCO',
        'lon': '-115.083336',
        'iso': 'CA',
        'status': 1,
        'name': 'Kugluktuk Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '67.833336',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCQ',
        'lon': '-121.63333',
        'iso': 'CA',
        'status': 1,
        'name': 'Chetwynd Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '55.683334',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCR',
        'lon': '-97.75144',
        'iso': 'CA',
        'status': 1,
        'name': 'Cross Lake (Charlie Sinclair Memorial) Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '54.61306',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCS',
        'lon': '-90.71667',
        'iso': 'CA',
        'status': 1,
        'name': 'Chesterfield Inlet Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '63.333332',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCV',
        'iso': 'CA',
        'status': 0,
        'name': 'Cartierville Airport',
        'continent': 'NA',
        'type': 'closed',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YCX',
        'iso': 'CA',
        'status': 1,
        'name': 'CFB Gagetown Heliport',
        'continent': 'NA',
        'type': 'heliport',
        'size': null
    } as AirportInfo,
    {
        'iata': 'YCY',
        'lon': '-68.5',
        'iso': 'CA',
        'status': 1,
        'name': 'Clyde River Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '70.416664',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YCZ',
        'lon': '-115.87361',
        'iso': 'CA',
        'status': 1,
        'name': 'Fairmont Hot Springs Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '50.331944',
        'size': 'small'
    } as AirportInfo,
    {
        'iata': 'YDA',
        'lon': '-139.12083',
        'iso': 'CA',
        'status': 1,
        'name': 'Dawson City Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '64.041664',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YDB',
        'lon': '-139.01666',
        'iso': 'CA',
        'status': 1,
        'name': 'Burwash Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '61.35',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YDF',
        'lon': '-57.399727',
        'iso': 'CA',
        'status': 1,
        'name': 'Deer Lake Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '49.21027',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YDM',
        'lon': '138.8216',
        'iso': 'CA',
        'status': 1,
        'name': 'Ross River Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '-17.939201',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YDN',
        'lon': '-100.05',
        'iso': 'CA',
        'status': 1,
        'name': 'Dauphin Barker Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '51.1',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YDO',
        'lon': '-72.23333',
        'iso': 'CA',
        'status': 1,
        'name': 'Dolbeau St Felicien Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '48.86667',
        'size': 'medium'
    } as AirportInfo,
    {
        'iata': 'YDP',
        'lon': '-61.666668',
        'iso': 'CA',
        'status': 1,
        'name': 'Nain Airport',
        'continent': 'NA',
        'type': 'airport',
        'lat': '56.533333',
        'size': 'medium'
    } as AirportInfo
];
